"""add relationship and foreign keys

Revision ID: 1749be4b3c69
Revises: c6e8acdb2ac6
Create Date: 2024-07-11 21:48:58.960859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1749be4b3c69'
down_revision = 'c6e8acdb2ac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_name', sa.String(), nullable=True))
        batch_op.drop_column('name')

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('expense_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('expense_amount',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('expense_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('expense_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('category_name')

    # ### end Alembic commands ###
