"""add expenses_categories table

Revision ID: 200cab4b43c4
Revises: f99eb43e82e5
Create Date: 2024-07-12 14:47:31.967995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200cab4b43c4'
down_revision = 'f99eb43e82e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses_categories',
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_expenses_categories_category_id_category')),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], name=op.f('fk_expenses_categories_expense_id_expense')),
    sa.PrimaryKeyConstraint('expense_id', 'category_id')
    )
    op.drop_table('expensescategoies')
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(), nullable=True))

    op.create_table('expensescategoies',
    sa.Column('expense_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='fk_expensescategoies_category_id_category'),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], name='fk_expensescategoies_expense_id_expense'),
    sa.PrimaryKeyConstraint('expense_id', 'category_id')
    )
    op.drop_table('expenses_categories')
    # ### end Alembic commands ###
