"""update

Revision ID: 5597708ebdff
Revises: 8a096396c14f
Create Date: 2024-07-12 12:03:07.035571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5597708ebdff'
down_revision = '8a096396c14f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses_categories',
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_expenses_categories_category_id_category')),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], name=op.f('fk_expenses_categories_expense_id_expense')),
    sa.PrimaryKeyConstraint('expense_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses_categories')
    # ### end Alembic commands ###
