"""add relationship and foreign keys

Revision ID: c6e8acdb2ac6
Revises: c8c8be949b12
Create Date: 2024-07-11 19:24:56.287828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e8acdb2ac6'
down_revision = 'c8c8be949b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_name', sa.String(), nullable=False),
    sa.Column('expense_amount', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('paymode', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_expense_user_id_user')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('expenses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('expense_name', sa.VARCHAR(), nullable=False),
    sa.Column('expense_amount', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.VARCHAR(), nullable=True),
    sa.Column('paymode', sa.VARCHAR(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_expenses_user_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('expense')
    # ### end Alembic commands ###
