"""add association table

Revision ID: f99eb43e82e5
Revises: 5597708ebdff
Create Date: 2024-07-12 14:24:22.770359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f99eb43e82e5'
down_revision = '5597708ebdff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expensescategoies',
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_expensescategoies_category_id_category')),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], name=op.f('fk_expensescategoies_expense_id_expense')),
    sa.PrimaryKeyConstraint('expense_id', 'category_id')
    )
    op.drop_table('expenses_categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses_categories',
    sa.Column('expense_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='fk_expenses_categories_category_id_category'),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], name='fk_expenses_categories_expense_id_expense'),
    sa.PrimaryKeyConstraint('expense_id', 'category_id')
    )
    op.drop_table('expensescategoies')
    # ### end Alembic commands ###
